export const PROFILES = [
  {
   "time": "5\/24\/2024 14:31:30",
   "name": "이승은",
   "category": "Mobility",
   "en_name": "Seung-Eun Lee",
   "introduce": "반갑습니다. 디자이너 이승은입니다.",
   "product": "Heasy",
   "subject": "대중교통 연계형 접이식 전동 퍼스널 모빌리티",
   "email": "min1100777@gmail.com",
   "plant": "킹낭콩",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/24\/2024 23:11:50",
   "name": "김수현",
   "category": "Living",
   "en_name": "Su-Hyeon Kim",
   "introduce": "끝까지 가면 무엇이든 될 수 있다.",
   "product": "gging",
   "subject": "이끼를 활용한 친환경 실내용 공기정화가습기",
   "email": "ljc8620@naver.com",
   "instagram": "ruhxun_",
   "plant": "수바리",
   "seed": "바질"
  },
  {
   "time": "5\/25\/2024 17:12:27",
   "name": "김이연",
   "category": "Living",
   "en_name": "I-Youn Kim",
   "introduce": "사람들은 절 개미라고 부르곤 하죠. ",
   "product": "gging",
   "subject": "이끼를 활용한 친환경 실내용 공기정화가습기",
   "email": "gimmedus@gmail.com",
   "instagram": "gimgammie.design",
   "photopolio": "https:\/\/www.behance.net\/rladldus1233eb",
   "plant": "a perfect match for tomatoes",
   "seed": "바질"
  },
  {
   "time": "5\/25\/2024 21:02:21",
   "name": "정해민",
   "category": "Mobility",
   "en_name": "Hae-Min Jung",
   "introduce": "權不十年 花無十一紅",
   "product": "GlideSurf",
   "subject": "수상친화적 레저 스포츠 모빌리티",
   "email": "wjdgoals36@gmail.com",
   "instagram": "mean_o0",
   "plant": "키",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/25\/2024 23:11:49",
   "name": "김지민",
   "category": "Mobility",
   "en_name": "Ji-Min Kim",
   "introduce": "가장 깊은 공감은 애정에서 나온다.",
   "product": "ILLO",
   "subject": "전기차 충전 인프라의 효율을 높이기 위한 배터리 딜리버리 로봇",
   "email": "zmkk1107@gmail.com",
   "instagram": "dsgnr_zmkk",
   "photopolio": "https:\/\/zmkk.myportfolio.com",
   "plant": "콩밥이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 14:38:04",
   "name": "이시온",
   "category": "Care",
   "en_name": "Si-On Lee",
   "introduce": "안되면 되는 걸 하자",
   "product": "WalkMate",
   "subject": "보행 시 낙상의 위험을 줄여주는 보행보조차",
   "email": "ls9382@naver.com",
   "plant": "쵸파",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 14:44:44",
   "name": "박지윤",
   "category": "Living",
   "en_name": "Ji-Yun Park",
   "introduce": "Time for us to shine",
   "product": "맡겨줄개",
   "subject": "편의점 출입 시 이용하는 반려견 맡김 서비스",
   "email": "oa3b49k@naver.com",
   "plant": "쑥쑥이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 15:35:43",
   "name": "이수빈",
   "category": "Mobility",
   "en_name": "Soo-Bin Lee",
   "introduce": "독창적인 디자인으로 편리함을 만들자",
   "product": "Climb",
   "subject": "계단 청소를 도와주는 스텝 클라이머",
   "email": "beenigood@naver.com",
   "instagram": "bslooe",
   "plant": "수빈 아닌 얼룩강낭빈",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 15:43:28",
   "name": "신동찬",
   "category": "Living",
   "en_name": "Dong-Chan Shin",
   "introduce": "빠르게 가지 말고 바르게 가자. ",
   "product": "futri",
   "subject": "패치 섭취 기술을 이용한 커스텀 패치 생성기, 웨어러블 기기",
   "email": "goodday616@gmail.com",
   "instagram": "chann6__",
   "plant": "동동이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 16:24:01",
   "name": "김익현",
   "category": "Care",
   "en_name": "Ik-Hyeon Kim",
   "introduce": "못먹어도 고",
   "product": "EZ-Beesy",
   "subject": "소방관을 위한 휴대용 벌 포집기",
   "email": "dlrgus0313@naver.com",
   "instagram": "dlrgus0313",
   "plant": "세바스챤",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 18:14:23",
   "name": "백승선",
   "category": "Mobility",
   "en_name": "Seung-Seon Baek",
   "introduce": "의심하는 디자이너 백승선입니다.",
   "product": "ILLO",
   "subject": "전기차 충전 인프라의 효율을 높이기 위한 배터리 딜리버리 로봇",
   "email": "bss1702a@gmail.com",
   "instagram": "baek.design",
   "photopolio": "https:\/\/baekdesign.myportfolio.com\/",
   "plant": "달빛바다속푸른하늘위숲속작은나무",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 18:56:22",
   "name": "박채연",
   "category": "Care",
   "en_name": "Chae-Yeon Park",
   "introduce": "하고 싶은 게 많은 디자이너",
   "product": "Savuoy",
   "subject": "이안류에 대비한 구조용 부표",
   "email": "itsmecyp@gmail.com",
   "instagram": "works_cy",
   "plant": "총총이",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 19:16:31",
   "name": "김승규",
   "category": "Care",
   "en_name": "Seung-Gyu Kim",
   "introduce": "달걀은 익으면 끝이다",
   "product": "EZ-Beesy",
   "subject": "소방관들을 위한 휴대용 벌 포집기",
   "email": "ksgdragon@naver.com",
   "plant": "수육",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 20:14:35",
   "name": "최성우",
   "category": "Living",
   "en_name": "Sung-Woo Choi",
   "introduce": "Slow down and enjoy",
   "product": "futri",
   "subject": "패치 섭취 기술을 이용한 커스텀 패치 생성기, 웨어러블 기기",
   "email": "swoo5239@naver.com",
   "instagram": "seongu260",
   "plant": "바질 아블로",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 20:21:28",
   "name": "이한",
   "category": "Living",
   "en_name": "Han Lee",
   "introduce": "안녕하세요. 저는 [더보기···]",
   "product": "RE-VER",
   "subject": "지렛대 원리를 활용한 캡슐분리 커피머신",
   "email": "dlgks218@gmail.com",
   "plant": "꽁꽁이",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 20:58:54",
   "name": "강호정",
   "category": "Mobility",
   "en_name": "Ho-Jeong Kang",
   "introduce": "순간순간 행복하기",
   "product": "Seader",
   "subject": "바다숲 복원을 돕는 잘피 이식 모빌리티",
   "email": "rkdghwjd0116@naver.com",
   "instagram": "s",
   "photopolio": "https:\/\/www.behance.net\/aa0b8d0b",
   "plant": "강냉이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 21:17:59",
   "name": "최혁수",
   "category": "Care",
   "en_name": "Hyeok-Su Choi",
   "introduce": "비열한 성공보다는 진실된 실패를",
   "product": "Savuoy",
   "subject": "이안류에 대비한 구조용 부표",
   "email": "grandchoi7194@gmail.com",
   "instagram": "from_five_ceramics",
   "plant": "까망",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 21:28:51",
   "name": "신민우",
   "category": "Mobility",
   "en_name": "Min-Woo Shin",
   "introduce": "내 길을 달리고 이루고 날아가 함께",
   "product": "Heasy",
   "subject": "대중교통 연계형 접이식 퍼스널 모빌리티",
   "email": "tlsalsdn1021@gmail.com",
   "instagram": "ming_gu1021",
   "plant": "메르세데스 빈츠",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 21:42:08",
   "name": "김혜민",
   "category": "Mobility",
   "en_name": "Hye-Min Kim ",
   "introduce": "안녕하세요, 디자이너 김혜민입니다.",
   "product": "Climb",
   "subject": "계단 청소를 도와주는 스텝 클라이머",
   "email": "yo_dream_js@naver.com",
   "instagram": "the__autum.n",
   "photopolio": "wittydesign.creatorlink.net",
   "plant": "얼콩이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 21:54:55",
   "name": "김호빈",
   "category": "Living",
   "en_name": "Ho-Been Kim",
   "introduce": "심플함 속에 담긴 디자인",
   "product": "PlayBook",
   "subject": "무선 디스플레이 기술을 활용한 게이밍 폼팩터",
   "email": "ehb715@naver.com",
   "plant": "달짝이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 22:22:31",
   "name": "천세강",
   "category": "Care",
   "en_name": "Se-Kang Chun",
   "introduce": "항상 즉시 기쁘게 다시 시작하자",
   "product": "Joynt",
   "subject": "휠체어 탈착이 가능한 관절구축 예방 재활 기기",
   "email": "chunsekang@gmail.com",
   "plant": "천개초",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 22:23:49",
   "name": "윤채원",
   "category": "Living",
   "en_name": "Chae-Won Yun",
   "introduce": "안녕하세요 디자인공학과 윤채원입니다.",
   "product": "맡겨줄개",
   "subject": "편의점 출입 시 이용하는 반려견 맡김 서비스",
   "email": "dbscodnjs01@naver.com",
   "plant": "바질이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 22:31:26",
   "name": "오기석",
   "category": "Care",
   "en_name": "Ki-Seok Oh",
   "introduce": "요즘 날씨 참 좋네, 나 같아",
   "product": "Roof",
   "subject": "구조 대원 매몰 사고를 대비한 웨어러블 장비",
   "email": "okshope@naver.com",
   "instagram": "7l.ssk",
   "plant": "기싹",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 22:28:31",
   "name": "김정연",
   "category": "Living",
   "en_name": "Jeong-Yeon Kim",
   "introduce": "공감이 담긴 디자인을 위한 첫걸음",
   "product": "Aira",
   "subject": "보행이 어려운 반려견을 위한 휠체어",
   "email": "kyjmsd@gmail.com",
   "plant": "라온힐조",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 22:38:13",
   "name": "박정빈",
   "category": "Living",
   "en_name": "Jung-Bin Park",
   "introduce": "NOW OR NEVER",
   "product": "북르륵",
   "subject": "도서관 사서를 위한 북 카트 디자인",
   "email": "jb0201200@naver.com",
   "plant": "새싹이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 22:50:05",
   "name": "김채은",
   "category": "Living",
   "en_name": "Chae-Eun Kim",
   "introduce": "be you",
   "product": "북르륵",
   "subject": "도서관 사서를 위한 북 카트 디자인",
   "email": "omeoul@gmail.com",
   "instagram": "codmso",
   "photopolio": "https:\/\/cekim-portfolio.framer.website\/",
   "plant": "메롱식물이",
   "seed": "바질"
  },
  {
   "time": "5\/26\/2024 23:09:30",
   "name": "조용현",
   "category": "Mobility",
   "en_name": "Yong-Hyeon Cho",
   "introduce": "부족한 작품이지만 잘 부탁드립니다.",
   "product": "Stretchroller",
   "subject": "차량 탑승에 편의성을 고려한 대형견 유모차",
   "email": "dydgus9130@gmail.com",
   "plant": "별무늬",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 23:14:25",
   "name": "최민경",
   "category": "Care",
   "en_name": "Min-Kyeong Choe",
   "introduce": "앞으로도 힘내자!",
   "product": "WalkMate",
   "subject": "보행 시 낙상의 위험을 줄여주는 보행보조차",
   "email": "lunachoe02@gmail.com",
   "plant": "콩나물",
   "seed": "안개초"
  },
  {
   "time": "5\/26\/2024 23:20:27",
   "name": "사공도영",
   "category": "Mobility",
   "en_name": "Do-Young Sakong",
   "introduce": "새로운 꿈을 그리는 사람이 되겠습니다",
   "product": "GlideSurf",
   "subject": "수상친화적 레저 스포츠 모빌리티",
   "email": "do-young_design@naver.com",
   "instagram": "do.young_design",
   "photopolio": "www.linkedin.com\/in\/doyoung-design",
   "plant": "영룩이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/26\/2024 23:23:35",
   "name": "이서하",
   "category": "Mobility",
   "en_name": "Seo-Ha Lee",
   "introduce": "충실한 오늘",
   "product": "Hiking",
   "subject": "허리 건강을 위한 높이조절 전동 쇼핑카트",
   "email": "fomular135@gmail.com",
   "plant": "자라자",
   "seed": "바질"
  },
  {
   "time": "5\/27\/2024 2:11:33",
   "name": "김도훈",
   "category": "Living",
   "en_name": "Do-Hoon Kim",
   "introduce": "2024 졸업전시 화이팅",
   "product": "PlayBook",
   "subject": "무선 디스플레이를 활용한 게이밍폼팩터",
   "email": "kimdohoon158@gmail.com",
   "instagram": "dod.___.an",
   "plant": "말린망고",
   "seed": "바질"
  },
  {
   "time": "5\/27\/2024 3:42:07",
   "name": "곽우령",
   "category": "Mobility",
   "en_name": "Woo-Ryoung Kwak",
   "introduce": "힘들어도 그냥 하면 이게 되네...?",
   "product": "Scroll",
   "subject": "2차사고 방지를 위한 차량용 안전삼각대",
   "email": "dnfud21@gmail.com",
   "plant": "막냉이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/27\/2024 10:09:12",
   "name": "김다준",
   "category": "Mobility",
   "en_name": "Da-Joon Kim",
   "introduce": "낙타는 뛸 줄 알지만, 뛰지 않는다",
   "product": "Seader",
   "subject": "바다숲 복원을 돕는 잘피 이식 모빌리티",
   "email": "dajoon0417@naver.com",
   "instagram": "give_todo",
   "photopolio": "https:\/\/www.behance.net\/dajoonkim",
   "plant": "다식이",
   "seed": "얼룩강낭콩"
  },
  {
   "time": "5\/27\/2024 14:43:37",
   "name": "이예빈",
   "category": "Care",
   "en_name": "Ye-Bin Lee",
   "introduce": "공감을 통해 디자인하는 대학생입니다",
   "product": "Fegeres",
   "subject": "공공장소 방패형 소화기",
   "email": "youmylife41@naver.com",
   "instagram": "yeppi_n",
   "plant": "안나",
   "seed": "안개초"
  },
  {
   "time": "5\/27\/2024 17:29:26",
   "name": "황민성",
   "category": "Care",
   "en_name": "Min-Seong Hwang",
   "introduce": "기회는 직접 찾는 거야",
   "product": "Joynt",
   "subject": "휠체어 탈착이 가능한 관절구축 예방 재활기기",
   "email": "rkd0206tjs@naver.com",
   "instagram": "mnsng_00",
   "plant": "캐서린",
   "seed": "안개초"
  },
  {
   "time": "5\/27\/2024 23:25:00",
   "name": "최성일",
   "category": "Care",
   "en_name": "Seong-Il Choe",
   "introduce": "긍정적인 영향력을 더 멀리 멀리",
   "product": "FORTO",
   "subject": "업사이클링을 통한 영유아 케어용 조립식 가구",
   "email": "sungil3816@gmail.com",
   "instagram": "sungil3816",
   "plant": "계란보끔밥",
   "seed": "안개초"
  },
  {
   "time": "5\/27\/2024 23:42:35",
   "name": "김두언",
   "category": "Care",
   "en_name": "Du-Eon Kim",
   "introduce": "더디어도 확실하게 차곡차곡 ",
   "product": "FORTO",
   "subject": "업사이클링을 통한 영유아 케어용 조립식 가구",
   "email": "igniter7@naver.com",
   "instagram": "uoanp._",
   "plant": "둥둥이",
   "seed": "안개초"
  },
  {
   "time": "5\/28\/2024 3:39:17",
   "name": "원윤섭",
   "category": "Mobility",
   "en_name": "Yoon-Seop Won",
   "introduce": "역경을 헤치고 별을 향하여",
   "product": "Soffi",
   "subject": "퍼스널 모빌리티 사용자를 위한 헬멧 살균기",
   "email": "yoonseop369@gmail.com",
   "plant": "콩이",
   "seed": "얼룩강낭콩"
  }
 ]